[package]
name = "http_dump"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version="0.8.8", features = ["ws", "http2", "macros"] }
#serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
#tower-http = { version = "0.6", features = ["fs"] }
tower ="0.5.3"
http-body-util = "0.1.0"
#axum-embed = "0.1.0"
rust-embed = "8.10.0"
mime_guess ="2.0.5"